// Hidden, isolated renderer test. Does not launch the user's app or access Keychain.
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'jev-renderer-test-'));
app.setPath('userData', temporary);
app.whenReady().then(async () => {
  const window = new BrowserWindow({ show: false, width: 1220, height: 820, webPreferences: { preload: path.join(__dirname, 'renderer-preload.cjs'), contextIsolation: true, sandbox: true, backgroundThrottling: false } });
  try {
    await window.loadFile(path.resolve(__dirname, '../ui/index.html'));
    const result = await window.webContents.executeJavaScript(`(async () => {
      const check = (condition, message) => { if (!condition) throw new Error(message); };
      check(document.body.classList.contains('compact'), 'App did not start compact');
      check(window.testSearch.lastLayout() === 'bar', 'Initial native layout is not a bar');
      await startSearch('project');
      check(window.testSearch.lastLayout() === 'results', 'Search did not expand the window');
      const hits = Array.from({ length: 500 }, (_, i) => ({ name: 'Project ' + i, path: '/demo/project-' + i, relative: 'Project ' + i, kind: i % 2 ? 'code' : 'document', size: 100, modified: 1790000000, probability: .8, localScore: .9, rank: .9, excerpt: 'Example text', coverage: 'Text excerpt' }));
      const stats = { scanned: 21500, evaluated: 500, cost: .1, costReports: 10, requests: 10, elapsed: 3 };
      const emit = (changes = {}) => window.testSearch.emit({ id: 'fixture', type: 'results', phase: 'thinking', matchCount: 500, stats, ...changes });
      emit({ hits });
      const first = document.querySelector('.result-row');
      const firstContent = first.firstElementChild;
      selectResult(10);
      emit({ stats: { ...stats, cost: .2 } });
      check(document.querySelector('.result-row') === first, 'Progress updates recreated rows');
      check(first.firstElementChild === firstContent, 'Progress updates recreated row contents');
      check(document.querySelector('#search-cost-value').textContent === '$0.2000', 'Cost did not update');
      check(state.selected === hits[10].path, 'Selection was lost');
      emit({ hits: [hits[10], ...hits.slice(0, 10), ...hits.slice(11)] });
      check(document.querySelector('.result-name').textContent === 'Project 10', 'Ranking order did not update');
      check(document.querySelector('.result-row').getAttribute('aria-selected') === 'true', 'Selection did not follow file');
      emit({ hits: [{ ...hits[10], probability: .99 }, hits[11]] });
      check(document.querySelectorAll('.result-row').length === 2, 'Stale rows remained');
      check(document.querySelector('.score').textContent.includes('99%'), 'Probability did not update');
      document.querySelector('[data-filter="code"]').click();
      check(document.querySelectorAll('.result-row').length === 1, 'Filter did not update');
      emit({ phase: 'complete', hits: [hits[10], hits[11]] });
      check(document.querySelector('#search-cost-label').textContent === 'Search cost', 'Final cost label missing');
      check(!document.querySelector('#widen-button').classList.contains('hidden'), 'Look wider is missing');
      document.querySelector('#widen-button').click();
      await new Promise(resolve => setTimeout(resolve, 0));
      check(window.testSearch.lastSearch().mode === 'deep', 'Look wider did not select the full pass');
      check(window.testSearch.lastSearch().query === 'project', 'Look wider changed the query');
      check(document.querySelector('#search-cost-value').textContent === '$0.0000', 'Full pass cost did not reset');
      check(document.querySelector('#notice').textContent.includes('own cost total'), 'Wider-search cost reset is not explained');
      emit({ phase: 'complete', stats: { ...stats, mode: 'deep', scanComplete: true, sampled: 240 }, hits: [hits[11]] });
      check(document.querySelector('#widen-button').classList.contains('hidden'), 'Full pass still offers the same widening action');
      check(document.querySelector('#status-left').textContent.includes('240 files sampled'), 'Coverage count is missing');
      emit({ hits: [{ ...hits[11], size: null, modified: null, probability: null, matchSource: 'content' }] });
      check(document.querySelector('.local-source').textContent === 'TEXT', 'Local content match mislabeled');
      check(document.querySelector('.verification-label').textContent === 'Not JEV-checked', 'Unchecked row has no visible warning');
      check(document.querySelector('#results-total').textContent.includes('1 not JEV-checked'), 'Unchecked count missing');
      check(!document.querySelector('#detail').textContent.includes('1970'), 'Unknown date rendered as Unix epoch');
      check(document.querySelector('#detail').textContent.includes('MATCHING TEXT'), 'Unread-by-JEV text mislabeled');
      check(document.querySelector('#detail').textContent.includes('not JEV-checked'), 'Unchecked detail is misleading');
      const retainedRow = document.querySelector('.result-row');
      emit({ hits: [{ ...hits[11], probability: .9 }] });
      check(document.querySelector('.result-row') === retainedRow, 'Semantic approval recreated the row');
      check(!document.querySelector('.verification-label'), 'Approved result still labeled unchecked');
      check(document.querySelector('.score').textContent.includes('90%'), 'Approved score missing');
      emit({ phase: 'complete', matchCount: 0, stats: { ...stats, verifiedMatches: 0, unverifiedMatches: 0 }, hits: [] });
      check(document.querySelectorAll('.result-row').length === 0, 'Rejected result stayed visible');
      check(state.selected === null && document.querySelector('.detail-empty'), 'Removed result detail stayed visible');
      await startSearch('next query');
      check(document.querySelectorAll('.result-row').length === 0, 'Prior search rows survived');
      check(document.querySelector('#search-cost-value').textContent === '$0.0000', 'Cost did not reset');
      await clearSearch();
      check(window.testSearch.lastLayout() === 'bar', 'Clear did not collapse to a bar');
      document.querySelector('#layout-toggle').click();
      check(window.testSearch.lastLayout() === 'workspace' && !document.body.classList.contains('compact'), 'Workspace toggle failed');
      document.querySelector('#layout-toggle').click();
      check(window.testSearch.lastLayout() === 'bar', 'Workspace did not collapse');
      showSettings();
      check(window.testSearch.lastLayout() === 'settings', 'Settings opened inside a tiny bar');
      document.querySelector('#settings-close').click();
      await new Promise(resolve => setTimeout(resolve, 30));
      check(window.testSearch.lastLayout() === 'bar', 'Closing settings did not restore bar');
      await startSearch('project');
      document.querySelector('[data-filter="all"]').click();
      emit({ phase: 'complete', hits: [hits[0], hits[1]], matchCount: 2 });
      document.querySelector('#query').focus();
      document.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true }));
      check(state.selected === hits[0].path, 'First down-arrow skipped the first result');
      document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
      await new Promise(resolve => setTimeout(resolve, 0));
      check(window.testSearch.lastFileAction().file === hits[0].path, 'Enter from search input did not open selected result');
      check(window.testSearch.hidden(), 'Opening a file did not dismiss compact search');
      document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
      check(window.testSearch.lastLayout() === 'bar', 'Escape did not collapse results');
      return 'Renderer passed: stable rows, ranking, selection, cost, coverage, content labels, missing metadata, Look wider, mode and query forwarding, reset.';
    })()`);
    console.log(result);
  } catch (error) { console.error(error); process.exitCode = 1; }
  window.destroy(); app.quit();
});
